### ISSUE TITLE
Difficulties to build on alpine linux

### ISSUE THREAD

**Issue by ether42** [D-os/aports#3]
Hi there,

I tried to build the `dos-base` metapackage and its dependencies, thinking it would allow me to have a base system to chroot into, but I encountered some difficulties.
I had to fix some checksums to build and use `-d` option of `abuild` for `dos-base` to avoid a clash with alpine base files (since it tries to install the dependencies for the build) (`musl-utils` is also needed but not present in the repository it seems).
For some others packages, like `abuild`, libressl is needed but alpine ships with `openssl` that clashes too.

I think I surely missed something obvious (I'm quite new to alpine) like an available base tarball or a way to make a minimal chroot to build everything without clashing with alpine packages?

By the way, here are the modified checksums to make some packages build so far, if you are interested: https://github.com/D-os/aports/compare/master...ether42:dev

Regards.

**Comment by smokku** [comment]
Well... yes... The most "not so obvious" thing is, that these packages are not meant to build nor installed under Alpine. These are D/os packages and D/os is completely separate from Alpine - built from scratch.
I'm just using Alpine Package Manager and reusing some packages from Alpine. But this repo is fundamentally incompatible with Alpine.

BTW, I wonder - what got you here? ;-)
D/os is a work-in-progress and nowhere near usable yet and this repo is just a time-to-time sync, so I won't loose my work in case of hdd crash etc.

**Comment by ether42** [comment]
Oh I see, that makes sense.
Can I ask how do you bootstrap the system (if you use something like a stage 3 tarball as do Gentoo/Exherbo/...)?

To be honest, the project of starting a distribution with LLVM & Musl piqued my interest (and that's how I got there with a bit of googling, I found your post on http://www.openwall.com/lists/musl/2015/01/06/3). And since only the core components are available, that's easier to take a sneak peek and understand everything.

So, even if there is no official documentation I am still interested by any clue of how to setup a base environment.
Maybe I'll have the opportunity to help a bit in a way or another :)

**Comment by smokku** [comment]
I started with minimal installation of Alpine in chroot http://blog.bpiotrowski.pl/1896/instalacja-alpine-linux-z-poziomu-innej-dystrybucji/
Then I swapped/rebuilt component by component until I had a complete self-contained system. Basing on Alpine packages which already contain Musl fixes made it easier.
The hardest was switching from GCC to LLVM - namely dropping dependency on libgcc.a.

The process of installing a chroot able to rebuild itself is described at: https://github.com/D-os/aports/blob/master/core/README

**Comment by smokku** [comment]
BTW If you want to rebuild it yourself, work with d438a13d8cbb75ca1055 - this is roughly the state of the current distribution on ftp.d-os.eu - later commits are WIP and borked. There's something wrong with newer Musl/LLVM combination, that produces borked binaries and archives.

**Comment by ether42** [comment]
Well, I totally forgot the part on http://ftp.d-os.eu that was on your post on the mailing list, shame on me...
I'm closing the issue, no need to bother you more, thanks.

Is [this](https://github.com/D-os/aports/blob/FHS/FHS.txt) the filesystem hierarchy that is still planned?

**Comment by smokku** [comment]
Yes.
But I am focusing on building a working system first, then messing with directories. Changing both (FHS and compiler) at the same time makes isolating bugs difficult, so I started from scratch. But the FHS revolution is still pending TODO.
